import express  from "express";
import fileUpload from "../helper/multer";
import Authorization from"../middleware/Auntantication";
import { signup,login,updateUser,deleteUserById,GetUsers,userByid } from "../controller/userControllers";
const usersRoutes = express.Router();
usersRoutes.post("/signup",fileUpload.single("profile"),signup);
usersRoutes.post("/login", fileUpload.single("profile"),login);
usersRoutes.put("/update/:id", fileUpload.single("profile"), updateUser);
usersRoutes.delete("/delete/:id", deleteUserById);
usersRoutes.get("/view",Authorization,GetUsers);
usersRoutes.get("/view/:id",Authorization, userByid);
export default usersRoutes;